apiVersion: v1
kind: ConfigMap
metadata:
  name: usertestsys
  namespace: servpy
data:
  DB_HOST: '192.168.3.139'
  DB_DATABASE: 'AcadsocDataAnalysisAlgorithm_rel_202103171015'
  DEFAULT_QUESTION_REV: 'rel_202104151230'
  DB_USER: 'ZAHNwifWYSLbnVRmhuilOmrpaO/PIAg6rpWlIbiEz2iGzUb8oCXQrCu8fszBym28aXOMQYDamC5OXEsV2D6rPdqTkadA/miPNb6J6A/Dil9WD3UhvKzbTpnrKFbOUX6jl1FoG2d0/geeHz/x+IKGURE6CRG74hd3WOKWWfX+wvU='
  DB_PASSWD: 'E9528qNXvBYosBBZWWuqrzCYbVV3Kp1eTvE/+KP4zyM5iJbFxveC8gELg8ri332VIzaOFMA5qTroKadj+z5a0XCd+5eDVskevh18+hqbU0FHCbh2a2ZZT36a1ddwujqK1ENktHFtz4j+b/W6HM1PZUbjUpI/mS0kGqSVMGRSFpg='
  REDIS_HOST: '192.168.0.22'
  REDIS_PORT: '6379'
  REDIS_MAX_CONN: '10'
  REDIS_PASSWD: 'W92B/68Nuggs144rsPeIuNFRNz2GTLycghyJ/fxeKAE6yt2wmDhxi324k5TjiKZOc82v5tcbVbcKyFbI9W3L6IelryCx6J/Yy4Iy3Isls6AfSSlJp9eGc6Fx2RF0TshYH2b1h0xUnjHwvQe1sX/LZLqv72MMHX7Q/s0XT4Q50io='
  REDIS_EXPIRE: '86400'
  FILES_URL_PREFIX: 'https://dstrserv.acadsoc.com.cn/file'
  APPID: 'St8PI9NpEwTOHzyVpSNVyY1LOc9GHbtgTsL6fQtyxMM1dj32f7eos2WG18RXbzs8BXeq8RC5JKvHLo8/9BL3lLKpteYZFPZJY5ejzu5e4sX91cUA0Bhe1YKMyyTMzvNlByMOB4uQNh2Cd1ijXzcyQJ+1GaoQkCuZZK9AaIgWghk='
  APPSECRET: 'jOO+AfeLkK7hLdIDL6zYi7GNlam+AiQd8rMCD085xDw9bS5Zsb1az/ZZ8JKHx6o56cIIfETazrExIjqG9NuyHp7w2Cb44do4saPKdbGavWPtsKITZbfa1MdKfYZmLv3d3nWvlWQtTEKobyMvBDOGwLb+IX8dOlpFL3AmVzFInMM='
  XUNFEI_APPID: 'pTYzZZsDwPcd1y0HuHlLJh7sa/LskEd5/b+LIT3O++ttbgA03eyoQtOanv8onUaW858bLhCADACi0W6a8rw22BCuOKWCb0310fdcHXl7C/0E6nUW8fR4OV5F0n3msS5agxAjsY5MMqZV9exyZgH59lG4kARyDx0ai9jycS5VLXU='
  XUNFEI_APISECRET: '9CbLalYgaDNYUfFaMsBR7ZWF1dUsb5TCRLu4kejxV4ciHs5CEYOvJHc49QwAsv5XW/dychK7qfVW7Ceg68MmYGS8B4pbRQzYECtEqlyeY6dMkv627/7gFzAXijgq5gaJ20V1jRfBTaRrINbVZ/msyiZbDYtlGYKCHve8yX42z2U='
  XUNFEI_APIKEY: 'aoeWlkmg7IcZe40S2d0mTef73BwxadexIHNXO51u+lfQe2Xme5NBrljsP0+VSE9nwxA8lRaWlvkOn/uM0S1vtZAIhXPtXmYTdEoXc0M8I1bhjRj7OhlxzoIXGruuDHn+SdE5nY1zCX9F5qLUH9ps7nx08JE30iiXMgjbEgDUpEw='
  FAKE_SWITCH: 'on'
  INTERFACE_PORT: '8080'
  METRICS_PORT: '8090'
  LOG_LEVEL: 'warn'